### ISSUE TITLE
Artifacts in Godot 3.2

### ISSUE THREAD

**Issue by MrMinimal** [kb173/godot-volumetric-clouds#8]
Can't wait to try it out but it looks a bit off on my XUbuntu machine:
![delete](https://user-images.githubusercontent.com/8739690/77113067-6aba8200-6a2a-11ea-9656-d85d85c845f5.png)

If you need more information I'd be glad to provide it to you!
Can't wait for the project to advance.

**Comment by kb173** [comment]
Thanks for the report! That does look rather off. I'm on Xubuntu with Godot 3.2 as well, so I'd guess it's hardware-related... What graphics card are you using? I noticed that on integrated graphics, there can be graphical artifacts (though I haven't noticed anything this bad). I think that's either related to the 3D texture or just the complexity of the shader. I can try to do some testing for that.

In the Material of the `CloudRenderer` node, you should be able to change shader parameters of the clouds. Can you check if changing the 'Random Vector Offset Amount' or the 'Num Steps' does anything?

Do you get the same visuals when running the demo game?

**Comment by MrMinimal** [comment]
Thanks for taking the time to check this out!

I'm running on a Intel HD Graphics 615 (see screenshot).
I tested your suggestions and the result aren't too different.
![delete](https://user-images.githubusercontent.com/8739690/77236673-0f6ec800-6bc1-11ea-8040-a549009f8478.png)

If I can be of further assistance, I'd gladly help!

**Comment by kb173** [comment]
Ok! I managed to test it on two laptops, both with Intel HD 620 graphics; it worked fine on both aside from some quirks (like having to move the camera once). Seems like parts of the shader are either too complex or undefined on the 615... I'll try to write a minimal version of it for you to test, to see where exactly the issue might be. Thank you for your help!

**Comment by MrMinimal** [comment]
Sure thing, let me know what I should do whenever you have it ready!
I can't wait to test this in my flight simulator.

**Comment by clemens-tolboom** [comment]
Is this still a problem? ... there are some [commits done since 22 Mar 2020](https://github.com/kb173/godot-volumetric-clouds/commits/master)

**Comment by MrMinimal** [comment]
Sorry, I sold the hardware with the problems.
Looks fine on my current hardware:
AMD Ryzen 3 4300u with radeon graphics AMD Renoir.

Running Ubuntu 21.04

![Screenshot from 2021-08-03 10-58-43](https://user-images.githubusercontent.com/8739690/127988233-8d3836fd-ef66-4a24-82fa-6dabad172e6c.png)

**Comment by kb173** [comment]
Thanks for testing again, good to see it works!
And sorry for never sending that minimal version! I started working on it but got stuck and then forgot :sweat_smile:
